Imported RANCID 2.3.2 final.

diff --git a/bin/control_rancid.in b/bin/control_rancid.in
--- a/bin/control_rancid.in
+++ b/bin/control_rancid.in
@@ -1,6 +1,6 @@
 #! /bin/sh
 ##
-## $Id: control_rancid.in,v 1.85 2008/04/24 19:07:05 heas Exp $
+## $Id: control_rancid.in,v 1.87 2009/04/17 23:00:20 heas Exp $
 ##
 ## @PACKAGE@ @VERSION@
 ## Copyright (c) 1997-2008 by Terrapin Communications, Inc.
@@ -98,7 +98,7 @@ if [ $# -ge 1 ] ; then
 fi
 
 # Must specify a group on which to run rancid
-if [ $# -lt 1 ]; then
+if [ $# -lt 1 ] ; then
     echo 'must specify group'; exit 1
 else
     GROUP=$1
@@ -112,7 +112,7 @@ unset noclobber > /dev/null 2>&1
 
 # RCS system
 RCSSYS=${RCSSYS:=cvs};
-if [ $RCSSYS != "cvs" -a $RCSSYS != "svn" -a $RCSSYS != "git" ] ; then
+if [ $RCSSYS != "cvs" -a $RCSSYS != "svn" ] ; then
     echo "$RCSSYS is not a valid value for RCSSYS."
     exit 1
 fi
@@ -136,8 +136,7 @@ if [ $MAX_ROUNDS -lt 1 ] ; then
 fi
 
 # Bail if we do not have the necessary info to run
-if [ ! -d $DIR ]
-then
+if [ ! -d $DIR ] ; then
     echo "$DIR does not exist."
     echo "Run bin/rancid-cvs $GROUP to make all of the needed directories."
     (
@@ -152,75 +151,33 @@ then
 fi
 cd $DIR
 
-create_ignore () {
-    echo "*~"
-    echo "routers.added"
-    echo "routers.all"
-    echo "routers.all.new"
-    echo "routers.db"
-    echo "routers.deleted"
-    echo "routers.down"
-    echo "routers.down.new"
-    echo "routers.failed"
-    echo "routers.mail"
-    echo "routers.single"
-    echo "routers.up"
-    echo "routers.up.new"
-    echo "routers.up.missed"
-}
+# create a .cvsignore
+if [ ! -f .cvsignore ] ; then
+    rm -f .cvsignore
+    cat >.cvsignore <<EOF
+.cvsignore
+routers.all
+routers.down
+routers.up
+EOF
+    if [ $RCSSYS = svn ] ; then
+	svn propset svn:ignore -F .cvsignore .
+    fi
+fi
 
-case $RCSSYS in
-    cvs )
-	if [ ! -f .cvsignore ]; then
-	    rm -f .cvsignore
-	    create_ignore > .cvsignore
-	    cvs add .cvsignore
-	    cvs commit -m "Adding .cvsignore"
-	fi
-	;;
-    svn )
-	svn proplist . | grep -q 'svn:ignore'
-	if [ $? -ne 0 ]; then
-	    create_ignore > .svnignore
-	    svn propset svn:ignore -F .svnignore .
-	    svn commit -m "Adding svn:ignore"
-	    rm -f .svnignore
-	fi
-	;;
-    git )
-	if [ ! -f .gitignore ]; then
-	    rm -f .gitignore
-	    create_ignore > .gitignore
-	    (
-		flock -x 200
-		git add .gitignore
-		git commit -m "Adding .gitignore"
-	    ) 200>$BASEDIR/.lockfile
-	fi
-	;;
-esac
+# do cvs update of router.db in case anyone has fiddled.
+$RCSSYS update router.db > $TMP 2>&1
+grep "^C" $TMP > /dev/null
+if [ $? -eq 0 ] ; then
+    echo "There were $RCSSYS conflicts during update."
+    echo ""
+    cat $TMP
+    rm -f $TMP
+    exit 1
+fi
+rm -f $TMP
 
-case $RCSSYS in
-    cvs | svn )
-        # do cvs/svn update of router.db in case anyone has fiddled.
-	$RCSSYS update router.db > $TMP 2>&1
-	grep "^C" $TMP > /dev/null
-	if [ $? -eq 0 ] ; then
-	    echo "There were $RCSSYS conflicts during update."
-	    echo ""
-	    cat $TMP
-	    rm -f $TMP
-	    exit 1
-	fi
-	rm -f $TMP
-	;;
-    git )
-	# do nothing here (for now)
-	;;
-esac
-
-if [ ! -f $DIR/router.db ]
-then
+if [ ! -f $DIR/router.db ] ; then
     echo "$DIR/router.db does not exist."
     (
 	echo "To: $adminmailrcpt"
@@ -250,8 +207,7 @@ if [ ! -f routers.down ] ; then touch routers.down; fi
 if [ ! -f routers.up ] ; then touch routers.up; fi
 @DIFF_CMD@ routers.up routers.up.new > /dev/null 2>&1; RUP=$?
 
-if [ $RALL -ne 0 -o $RDOWN -ne 0 -o $RUP -ne 0 ]
-then
+if [ $RALL -ne 0 -o $RDOWN -ne 0 -o $RUP -ne 0 ] ; then
     (
 	if [ $RUP -ne 0 ] ; then
 	    if [ ! -s routers.up ] ; then
@@ -293,14 +249,12 @@ then
 	    WCADDED=`wc -l routers.added | sed -e 's/^ *\([^ ]*\) .*$/\1/'`
 	    WCDELETED=`wc -l routers.deleted | sed -e 's/^ *\([^ ]*\) .*$/\1/'`
 
-	    if [ $WCADDED -gt 0 ]
-	    then
+	    if [ $WCADDED -gt 0 ] ; then
 		echo Added routers:
 		cat routers.added
 		echo
 	    fi
-	    if [ $WCDELETED -gt 0 ]
-	    then
+	    if [ $WCDELETED -gt 0 ] ; then
 		echo Deleted routers:
 		cat routers.deleted
 		echo
@@ -324,27 +278,21 @@ then
     cd $DIR/configs
 
     # Add new routers to the CVS structure.
-    for router in `comm -13 $DIR/routers.up $DIR/routers.up.new | cut -d: -f1`
+    for router in `comm -13 $DIR/routers.up $DIR/routers.up.new`
     do
-	message="new router $router in group $GROUP"
+	OFS=$IFS
+	IFS=:
+	set $router
+	IFS=$OFS
+	router=$1
+
 	touch $router
-	case $RCSSYS in
-	    cvs )
-		cvs add -ko $router
-		cvs commit -m "$message" $router
-		;;
-	    svn )
-		svn add $router
-		svn commit -m "$message" $router
-		;;
-	    git )
-		(
-		    flock -x 200
-		    git add $router
-		    git commit -m "$message"
-		) 200>$BASEDIR/.lockfile
-		;;
-	esac
+	if [ $RCSSYS = cvs ] ; then
+	    cvs add -ko $router
+	else
+	    svn add $router
+	fi
+	$RCSSYS commit -m 'new router' $router
 	echo "Added $router"
     done
     echo
@@ -352,15 +300,15 @@ then
 
 fi
 mv -f routers.all.new routers.all
-if [ $? -ne 0 ]; then
+if [ $? -ne 0 ] ; then
     echo "Error: could not rename routers.all.new"
 fi
 mv -f routers.down.new routers.down
-if [ $? -ne 0 ]; then
+if [ $? -ne 0 ] ; then
     echo "Error: could not rename routers.down.new"
 fi
 mv -f routers.up.new routers.up
-if [ $? -ne 0 ]; then
+if [ $? -ne 0 ] ; then
     echo "Error: could not rename routers.up.new"
 fi
 rm -f routers.db
@@ -369,56 +317,29 @@ trap 'rm -fr $TMP;' 1 2 15
 cd $DIR/configs
 # check for 'up' routers missing in RCS.  no idea how this happens to some folks
 for router in `cut -d: -f1 ../routers.up` ; do
-    case $RCSSYS in
-	cvs )
-	    cvs status $router | grep -i 'status: unknown' > /dev/null 2>&1
-	    if [ $? -eq 0 ]; then
-		touch $router
-		cvs add -ko $router
-		echo "$RCSSYS added missing router $router"
-	    fi
-	    ;;
-	svn )
-	    svn status $router | grep '^?' > /dev/null 2>&1
-	    if [ $? -eq 0 ]; then
-		touch $router
-		svn add $router
-		echo "$RCSSYS added missing router $router"
-	    fi
-	    ;;
-	git )
-	    git ls-files $router > /dev/null 2>&1 
-	    if [ $? -eq 1 ]; then
-		touch $router
-		(
-		    flock -x 200
-		    git add $router
-		    git commit -m "added missing router $router"
-		) 200>$BASEDIR/.lockfile
-		echo "$RCSSYS added missing router $router"
-	    fi
-	    ;;
-    esac
+    if [ $RCSSYS = cvs ] ; then
+	cvs status $router | grep -i 'status: unknown' > /dev/null 2>&1
+    else
+	svn status $router | grep '^?' > /dev/null 2>&1
+    fi
+    if [ $? -eq 0 ] ; then
+	touch $router
+	if [ $RCSSYS = cvs ] ; then
+	    cvs add -ko $router
+	else
+	    svn add $router
+	fi
+	echo "$RCSSYS added missing router $router"
+    fi
 done
 echo
 # delete configs from RCS for routers not listed in routers.up.
-for router in `find . \( -name \*.new -prune -o -name CVS -prune -o -name .cvsignore -prune -o -name .svn -prune -o -name .git -prune -o -name .gitignore -prune \) -o -type f -print | sed -e 's/^.\///'` ; do
+for router in `find . \( -name \*.new -prune -o -name CVS -prune -o -name .svn -prune \) -o -type f -print | sed -e 's/^.\///'` ; do
     grep -i "^$router:" ../router.db > /dev/null 2>&1
-    if [ $? -eq 1 ]; then
+    if [ $? -eq 1 ] ; then
 	rm -f $router
-	case $RCSSYS in
-	    cvs | svn )
-		$RCSSYS delete $router
-		$RCSSYS commit -m "deleted router $router" $router
-		;;
-	    git )
-		(
-		    flock -x 200
-		    git rm $router
-		    git commit -m "deleted router $router"
-		) 200>$BASEDIR/.lockfile
-		;;
-	esac
+	$RCSSYS delete $router
+	$RCSSYS commit -m 'deleted router' $router
 	echo "Deleted $router"
     fi
 done
@@ -428,19 +349,7 @@ cd $DIR
 if [ ! -s routers.up ]
 then
     # commit router.db
-    message="updates of group $GROUP"
-    case $RCSSYS in
-	cvs | svn )
-	    $RCSSYS commit -m "$message" router.db
-	    ;;
-	git )
-	    (
-		flock -x 200
-		git add router.db
-		git commit -m "$message"
-	    ) 200>$BASEDIR/.lockfile
-	    ;;
-    esac
+    $RCSSYS commit -m updates router.db
     exit;
 fi
 
@@ -470,7 +379,7 @@ par -q -n $PAR_COUNT -c "rancid-fe {}" $devlistfile
 # $pass times.
 pass=$MAX_ROUNDS
 round=1
-if [ -f $DIR/routers.up.missed ]; then
+if [ -f $DIR/routers.up.missed ] ; then
     rm -f $DIR/routers.up.missed
 fi
 while [ $round -le $pass ]
@@ -490,7 +399,7 @@ do
 	fi
     done
 
-    if [ -f $DIR/routers.up.missed ]; then
+    if [ -f $DIR/routers.up.missed ] ; then
 	echo "====================================="
 	echo "Getting missed routers: round $round."
 	par -q -n $PAR_COUNT -c "rancid-fe \{}" $DIR/routers.up.missed
@@ -505,22 +414,26 @@ echo
 
 # Make sure that no empty/truncated configs are accepted.  The remainder are
 # renamed from device_name.new -> device_name.
-for router in `cat $devlistfile | cut -d: -f1`
+for router in `cat $devlistfile`
 do
-    if [ ! -s $router.new ]
-    then
+    OFS=$IFS
+    IFS=':'
+    set $router
+    IFS=$OFS
+    router=$1;
+
+    if [ ! -s $router.new ] ; then
 	rm -f $router.new
     else
-	lines=`awk '{if (/^([-*!;#]|\/\*)/) { next; } lines++; \
+	lines=`awk '{if ($0 ~ /^([-*!;#]|\/\*)/) { next; } lines++; \
 		if (lines > 10) { print "1"; exit;}} \
 		END { if (lines < 10) {print "0";}}' $router.new`
 
-	if [ ! $lines ]
-	then
+	if [ ! $lines ] ; then
 	    rm -f $router.new
 	else
 	    mv $router.new $router
-	    if [ $? -ne 0 ]; then
+	    if [ $? -ne 0 ] ; then
 		echo "Error: could not rename $router.new to $router"
 		rm -f $router.new
 	    fi
@@ -528,54 +441,32 @@ do
     fi
 done
 
+# This has been different for different machines...
+# Diff the directory and then checkin.
+trap 'rm -fr $TMP $TMP.diff $DIR/routers.single;' 1 2 15
+cd $DIR
+if [ $RCSSYS = "cvs" ] ; then
+    cvs -f @DIFF_CMD@ -ko | sed -e '/^RCS file: /d' -e '/^--- /d' \
+	-e '/^+++ /d' -e 's/^\([-+ ]\)/\1 /' >$TMP.diff
+else
+    svn diff | sed -e '/^+++ /d' -e 's/^\([-+ ]\)/\1 /' >$TMP.diff
+fi
+
 if [ $alt_mailrcpt -eq 1 ] ; then
     subject="router config diffs - courtesy of $mailrcpt"
 else
     subject="router config diffs"
 fi
 if [ "X$device" != "X" ] ; then
-    message="updates of group $GROUP - courtesy of $mailrcpt"
+    $RCSSYS commit -m "updates - courtesy of $mailrcpt"
     subject="$GROUP/$device $subject"
 else
-    message="updates of group $GROUP"
+    $RCSSYS commit -m updates
     subject="$GROUP $subject"
 fi
 
-# This has been different for different machines...
-# Diff the directory and then checkin.
-trap 'rm -fr $TMP $TMP.diff $DIR/routers.single;' 1 2 15
-cd $DIR
-case $RCSSYS in
-    cvs )
-	cvs -f @DIFF_CMD@ -ko | sed -e '/^RCS file: /d' -e '/^--- /d' \
-	    -e '/^+++ /d' -e 's/^\([-+ ]\)/\1 /' >$TMP.diff
-	cvs commit -m "$message"
-	;;
-    svn )
-	svn diff | sed -e '/^+++ /d' -e 's/^\([-+ ]\)/\1 /' >$TMP.diff
-	svn commit -m "$message"
-	;;
-    git )
-	# with git we do things differently - first commit, then grab the diff
-	(
-	    flock -x 200
-	    git add router.db
-	    for router in `cat $devlistfile | cut -d: -f1`
-	    do
-	      git add configs/$router
-	    done
-	    git commit -m "$message"
-	    if [ $? -eq 0 ]; then
-		# only generate a diff if the commit was successful
-		git diff --patch-with-stat HEAD^ HEAD -- . >$TMP.diff
-	    fi
-	) 200>$BASEDIR/.lockfile
-	;;
-esac
-
 # Mail out the diffs (if there are any).
-if [ -s $TMP.diff ]
-then
+if [ -s $TMP.diff ] ; then
 	(
 	  echo "To: $mailrcpt"
 	  echo "Subject: $subject"
@@ -594,8 +485,7 @@ if [ "X$OLDTIME" = "X" ] ; then
 fi
 @PERLV@ -F: -ane "{\$t = (stat(\$F[0]))[9]; print \`ls -ld \$F[0]\`
 	if (time() - \$t >= $OLDTIME*60*60);}" $devlistfile | sort -u > $DIR/routers.failed
-if [ -s $DIR/routers.failed ]
-then
+if [ -s $DIR/routers.failed ] ; then
 	(
 	  echo "To: $adminmailrcpt"
 	  echo "Subject: config fetcher problems - $GROUP"
