Imported from rancid-2.3.7.tar.gz

diff --git a/bin/mtlogin.in b/bin/mtlogin.in
--- a/bin/mtlogin.in
+++ b/bin/mtlogin.in
@@ -1,6 +1,6 @@
 #! @EXPECT_PATH@ --
 ##
-## $Id: jlogin.in 2370 2012-01-30 21:59:23Z heas $
+## $Id$
 ##
 ## @PACKAGE@ @VERSION@
 ## Copyright (c) @COPYYEARS@ by Terrapin Communications, Inc.
@@ -39,22 +39,22 @@
 ## CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 ## ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 ## POSSIBILITY OF SUCH DAMAGE.
-# 
-#  The expect login scripts were based on Erik Sherk's gwtn, by permission.
 #
-# jlogin - juniper login
+# The login expect scripts were based on Erik Sherk's gwtn, by permission.
 #
-# Most options are intuitive for logging into a Cisco router.
-# The default username password is the same as the vty password.
+# mtlogin - MikroTik router login
+#
+# bootc@bootc.net wrote this (Chris Boot)
 #
 
 # Usage line
-set usage "Usage: $argv0 \[-dSV\] \[-c command\] \[-Evar=x\] \
-\[-f cloginrc-file\] \[-p user-password\] \[-r passphrase\] \[-s script-file\] \
-\[-u username\] \[-t timeout\] \[-x command-file\] \[-y ssh_cypher_type\] \
-router \[router...\]\n"
+set usage "Usage: $argv0 \[-dV\] \[-c command\] \
+\[-Evar=x\] \[-f cloginrc-file\] \
+\[-s script-file\] \[-t timeout\] \[-u username\] \
+\[-v vty-password\] \[-x command-file\] \
+\[-y ssh_cypher_type\] router \[router...\]\n"
 
-# env(CLOGIN) may contain the following chars:
+# env(CLOGIN) may contain:
 #	x == do not set xterm banner or name
 
 # Password file
@@ -64,13 +64,14 @@ set do_command 0
 set do_script 0
 # The default is to automatically enable
 set avenable 1
+# The default is that you login non-enabled (tacacs can have you login already
+# enabled)
+set avautoenable 0
 # The default is to look in the password file to find the passwords.  This
 # tracks if we receive them on the command line.
 set do_passwd 1
-# Save config, if prompted
-set do_saveconfig 0
 # Sometimes routers take awhile to answer (the default is 10 sec)
-set timeoutdflt 120
+set timeout 45
 
 # Find the user in the ENV, or use the unix userid.
 if {[ info exists env(CISCO_USER) ]} {
@@ -98,53 +99,56 @@ for {set i 0} {$i < $argc} {incr i} {
     set arg [lindex $argv $i]
 
     switch  -glob -- $arg {
+	# Expect debug mode
+	-d* {
+	    exp_internal 1
+	# Username
+	} -u* -
+	-U* {
+	    if {! [  regexp .\[uU\](.+) $arg ignore user]} {
+		incr i
+		set username [ lindex $argv $i ]
+	    }
+	# VTY Password
+	} -v* {
+	    if {! [  regexp .\[vV\](.+) $arg ignore passwd]} {
+		incr i
+		set passwd [ lindex $argv $i ]
+	    }
+	    set do_passwd 0
+	# Version string
+	} -V* {
+	    send_user "rancid 2.3.2a9\n"
+	    exit 0
+	# Enable Username
+	} -w* -
+	-W* {
+	# ignore -w
+	# Environment variable to pass to -s scripts
+	} -E*
+	{
+	    if {[ regexp .\[E\](.+)=(.+) $arg ignore varname varvalue]} {
+		incr i
+		set E$varname $varvalue
+	    } else {
+		send_user "\nError: invalid format for -E in $arg\n"
+		exit 1
+	    }
+	# Enable Password
+	} -e*
+	{
+	# ignore -e
 	# Command to run.
-	-c* -
+	} -c* -
 	-C* {
 	    if {! [  regexp .\[cC\](.+) $arg ignore command]} {
 		incr i
 		set command [ lindex $argv $i ]
 	    }
 	    set do_command 1
-	# Expect debug mode
-	} -d* {
-	    exp_internal 1
-	# Environment variable to pass to -s scripts
-	} -E* {
-	    if {[ regexp .\[E\](.+)=(.+) $arg ignore varname varvalue]} {
-		set E$varname $varvalue
-	    } else {
-		send_user "\nError: invalid format for -E in $arg\n"
-		exit 1
-	    }
-	# alternate cloginrc file
-	} -f* {
-	    if {! [ regexp .\[fF\](.+) $arg ignore password_file]} {
-		incr i
-		set password_file [ lindex $argv $i ]
-	    }
-	# user Password
-	} -p* {
-	    if {! [  regexp .\[pP\](.+) $arg ignore userpasswd]} {
-		incr i
-		set userpasswd [ lindex $argv $i ]
-	    }
-	    set do_passwd 0
-	# ssh passphrase
-	} -r* {
-	    if {! [  regexp .\[rR\](.+) $arg ignore passphrase]} {
-		incr i
-		set avpassphrase [ lindex $argv $i ]
-	    }
-	# VTY Password
-	} -v* {
-	    # ignore -v
-	# Version string
-	} -V* {
-	    send_user "@PACKAGE@ @VERSION@\n"
-	    exit 0
 	# Expect script to run.
-	} -s* {
+	} -s* -
+	-S* {
 	    if {! [  regexp .\[sS\](.+) $arg ignore sfile]} {
 		incr i
 		set sfile [ lindex $argv $i ]
@@ -154,23 +158,30 @@ for {set i 0} {$i < $argc} {incr i} {
 		exit 1
 	    }
 	    set do_script 1
-	# save config on exit
-	} -S* {
-	    set do_saveconfig 1
+	# 'ssh -c' cypher type
+	} -y* -
+	-Y* {
+	    if {! [  regexp .\[eE\](.+) $arg ignore cypher]} {
+		incr i
+		set cypher [ lindex $argv $i ]
+	    }
+	# alternate cloginrc file
+	} -f* -
+	-F* {
+	    if {! [ regexp .\[fF\](.+) $arg ignore password_file]} {
+		incr i
+		set password_file [ lindex $argv $i ]
+	    }
 	# Timeout
-	} -t* {
+	} -t* -
+	-T* {
 	    if {! [ regexp .\[tT\](.+) $arg ignore timeout]} {
 		incr i
-		set timeoutdflt [ lindex $argv $i ]
+	        set timeout [ lindex $argv $i ]
 	    }
-	# Username
-	} -u* {
-	    if {! [  regexp .\[uU\](.+) $arg ignore user]} {
-		incr i
-		set username [ lindex $argv $i ]
-	    }
-	# command file
-	} -x* {
+	# Command file
+	} -x* -
+	-X {
 	    if {! [  regexp .\[xX\](.+) $arg ignore cmd_file]} {
 		incr i
 		set cmd_file [ lindex $argv $i ]
@@ -179,16 +190,16 @@ for {set i 0} {$i < $argc} {incr i} {
 		send_user "\nError: $reason\n"
 		exit 1
 	    }
-            set cmd_text [read $cmd_fd]
-            close $cmd_fd
-            set command [join [split $cmd_text \n] \;]
-            set do_command 1
-	# 'ssh -c' cypher type
-	} -y* {
-	    if {! [  regexp .\[yY\](.+) $arg ignore cypher]} {
-		incr i
-		set cypher [ lindex $argv $i ]
-	    }
+	    set cmd_text [read $cmd_fd]
+	    close $cmd_fd
+	    set command [join [split $cmd_text \n] \;]
+	    set do_command 1
+	# Do we enable?
+	} -noenable {
+	    # ignore -noenable
+	# Does tacacs automatically enable us?
+	} -autoenable {
+	    # ignore -autoenable
 	} -* {
 	    send_user "\nError: Unknown argument! $arg\n"
 	    send_user $usage
@@ -227,14 +238,14 @@ proc label { host } {
 	if [regexp \^(xterm|vs) $env(TERM) ignore ] {
 	    send_user "\033]1;[lindex [split $host "."] 0]\a"
 	    send_user "\033]2;$host\a"
-        }
+	}
     }
 }
 
 # This is a helper function to make the password file easier to
 # maintain.  Using this the password file has the form:
-# add password sl* 	pete cow
-# add password at* 	steve
+# add password sl*	pete cow
+# add password at*	steve
 # add password *	hanky-pie
 proc add {var args} { global int_$var ; lappend int_$var $args}
 proc include {args} {
@@ -247,15 +258,15 @@ proc include {args} {
 }
 
 proc find {var router} {
-  upvar int_$var list
-  if { [info exists list] } {
-    foreach line $list {
-      if { [string match [lindex $line 0] $router ] } {
-	return [lrange $line 1 end]
-      }
+    upvar int_$var list
+    if { [info exists list] } {
+	foreach line $list {
+	    if { [string match [lindex $line 0] $router ] } {
+		return [lrange $line 1 end]
+	    }
+	}
     }
-  }
-  return {}
+    return {}
 }
 
 # Loads the password file.  Note that as this file is tcl, and that
@@ -282,10 +293,11 @@ proc source_password_file { password_file } {
 
 # Log into the router.
 # returns: 0 on success, 1 on failure
-proc login { router user passwd cmethod cyphertype identfile} {
-    global spawn_id in_proc do_command do_script passphrase prompt
-    global sshcmd
+proc login { router user userpswd passwd prompt cmethod cyphertype } {
+    global spawn_id in_proc do_command do_script
+    global u_prompt p_prompt sshcmd
     set in_proc 1
+    set uprompt_seen 0
 
     # try each of the connection methods in $cmethod until one is successful
     set progs [llength $cmethod]
@@ -303,127 +315,104 @@ proc login { router user passwd cmethod cyphertype identfile} {
 		return 1
 	    }
 	} elseif ![string compare $prog "ssh"] {
-	    # ssh to the router & try to login with or without an identfile.
-	    # We use two calls to spawn since spawn does not seem to parse
-	    # spaces correctly.
-	    regexp {ssh(:([^[:space:]]+))*} $prog methcmd suffix port
-	    set cmd $sshcmd
-	    if {"$port" != ""} {
-		set cmd "$cmd -p $port"
-	    }
-	    if {"$identfile" != ""} {
-		set cmd "$cmd -i $identfile"
-	    }
-	        set retval [ catch {eval spawn [split "$cmd -c $cyphertype -x -l $user $router" { }]} reason ]
-	    if { $retval } {
-		send_user "\nError: $sshcmd failed: $reason\n"
-		return 1
-	    }
+            if [ catch {spawn $sshcmd -c $cyphertype -x -l $user+ct $router} reason ] {
+                send_user "\nError: $sshcmd failed: $reason\n"
+                return 1
+            }
 	} elseif ![string compare $prog "rsh"] {
 	    send_error "\nError: unsupported method: rsh\n"
 	    if { $progs == 0 } {
 		return 1
 	    }
-	    continue
+	    continue;
 	} else {
-	    send_user "\nError: unknown connection method: $prog\n"
+            send_user "\nError: unknown connection method: $prog\n"
+            return 1
+	}
+        sleep 0.3
+
+    # This helps cleanup each expect clause.
+    expect_after {
+	timeout {
+	    send_user "\nError: TIMEOUT reached\n"
+	    catch {close}; catch {wait};
+	    if { $in_proc} {
+		return 1
+	    } else {
+		continue
+	    }
+	} eof {
+	    send_user "\nError: EOF received\n"
+	    catch {close}; catch {wait};
+	    if { $in_proc} {
+		return 1
+	    } else {
+		continue
+	    }
+	}
+    }
+
+    expect {
+	"Connection refused" {
+	    catch {close}; catch {wait};
+	    sleep 0.3
+		expect eof
+		send_user "\nError: Connection Refused\n"; wait; return 1
+	} eof { send_user "\nError: Couldn't login\n"; wait; return 1
+	} "Unknown host\r\n" {
+	    expect eof
+	    send_user "\nError: Unknown host\n"; wait; return 1
+	} "Host is unreachable" {
+	    expect eof
+	    send_user "\nError: Host Unreachable!\n"; wait; return 1
+	} "No address associated with name" {
+	    expect eof
+	    send_user "\nError: Unknown host\n"; wait; return 1
+	}
+	-re "(Host key not found |The authenticity of host .* be established).*\(yes\/no\)\\?" {
+	    send "yes\r"
+	    send_user "\nHost $router added to the list of known hosts.\n"
+	    exp_continue }
+	-re "HOST IDENTIFICATION HAS CHANGED.* \(yes\/no\)\\?"   {
+	    send "no\r"
+	    send_user "\nError: The host key for $router has changed.  Update the SSH known_hosts file accordingly.\n"
+	    return 1 }
+	-re "HOST IDENTIFICATION HAS CHANGED\[^\n\r]+" {
+	    send_user "\nError: The host key for $router has changed.  Update the SSH known_hosts file accordingly.\n"
 	    return 1
 	}
-	sleep 0.3
+	-re "Offending key for .* \(yes\/no\)\\?"   {
+	    send "no\r"
+	    send_user "\nError: host key mismatch for $router.  Update the SSH known_hosts file accordingly.\n"
+	    return 1 }
 
-	# This helps cleanup each expect clause.
-	expect_after {
-	    timeout {
-		send_user "\nError: TIMEOUT reached\n"
-		catch {close}; catch {wait};
-		if { $in_proc} {
-	            return 1
-		} else {
-	            continue
-		}
-            } eof {
-		send_user "\nError: EOF received\n"
-		catch {close}; catch {wait};
-		if { $in_proc} {
-	            return 1
-		} else {
-	            continue
-		}
-            }
-	}
-
-	# Here we get a little tricky.  There are several possibilities:
-	# the router can ask for a username and passwd and then
-	# talk to the TACACS server to authenticate you, or if the
-	# TACACS server is not working, then it will use the enable
-	# passwd.  Or, the router might not have TACACS turned on,
-	# then it will just send the passwd.
-	expect {
-	    -re "(Connection refused|Secure connection \[^\n\r]+ refused|Connection closed by)" {
-		catch {close}; catch {wait};
-		if !$progs {
-		   send_user "\nError: Connection Refused ($prog)\n"; return 1
-		}
-	    }
-            eof { send_user "\nError: Couldn't login\n"; wait; return 1
-	    } -nocase "unknown host\r\n" {
-		catch {close}; catch {wait};
-		send_user "\nError: Unknown host\n"; wait; return 1
-	    } "Host is unreachable" {
-		catch {close}; catch {wait};
-		send_user "\nError: Host Unreachable!\n"; wait; return 1
-	    } "No address associated with name" {
-		catch {close}; catch {wait};
-		send_user "\nError: Unknown host\n"; wait; return 1
-	    }
-	    "Login incorrect" {
-			  send_user "\nError: Check your password for $router\n"
+	-re "$u_prompt"			{
+					  send -- "$user+ct\r"
+					  set uprompt_seen 1
+					  exp_continue
+					}
+	-re "$p_prompt"			{
+					  sleep 1
+					  if {$uprompt_seen == 1} {
+						send -- "$userpswd\r"
+					  } else {
+						send -- "$passwd\r"
+					  }
+					  exp_continue
+					}
+	-re "^Confirm seeing above note" {
+					  send "y\r"
+					  exp_continue
+					}
+	"Password incorrect"	{ send_user "\nError: Check your password for $router\n";
+				  catch {close}; catch {wait}; return 1 }
+	-re "$prompt"	{ break; }
+	denied		{ send_user "\nError: Check your passwd for $router\n"
 			  catch {close}; catch {wait}; return 1
 			}
-	    -re "Enter passphrase.*: " {
-		# sleep briefly to allow time for stty -echo
-		sleep 1
-		send -- "$passphrase\r"
-		exp_continue }
-	    -re "(Host key not found |The authenticity of host .* be established).*\(yes\/no\)\\?" {
-		send "yes\r"
-		send_user "\nHost $router added to the list of known hosts.\n"
-		exp_continue }
-	    -re "HOST IDENTIFICATION HAS CHANGED.* \(yes\/no\)\\?" {
-		send "no\r"
-		send_user "\nError: The host key for $router has changed.  Update the SSH known_hosts file accordingly.\n"
-		return 1 }
-	    -re "HOST IDENTIFICATION HAS CHANGED\[^\n\r]+" {
-		send_user "\nError: The host key for $router has changed.  Update the SSH known_hosts file accordingly.\n"
-		return 1 }
-	    -re "Offending key for .* \(yes\/no\)\\?" {
-		send "no\r"
-		send_user "\nError: host key mismatch for $router.  Update the SSH known_hosts file accordingly.\n"
-		return 1 }
-	    -re "(Username|\[\r\n]login):"	{
-						  send -- "$user\r"
-						  exp_continue
-	    					}
-	    "\[Pp]assword:"			{
-						  sleep 1; send -- "$passwd\r"
-						  exp_continue
-						}
-	    -re "$prompt"		{ break; }
-	    denied	{ send_user "\nError: Check your password for $router\n"
-	                  catch {close}; catch {wait}; return 1
-	                }
-	}
+	"\r\n"		{ exp_continue; }
     }
-
-    # we are logged in, now figure out the full prompt
-    send "\r"
-    expect {
-	-re "(\r\n|\n)"		{ exp_continue; }
-	-re "^\[^ ]+$prompt"	{ set prompt $expect_out(0,string);
-				  regsub ">" $prompt "\[#>]" prompt;
-				}
-    }
-
+  }
     set in_proc 0
     return 0
 }
@@ -433,24 +422,26 @@ proc run_commands { prompt command } {
     global in_proc
     set in_proc 1
 
-    send "set cli complete-on-space off\r"
-    expect -re $prompt	{}
-    send "set cli screen-length 0\r"
-    expect -re $prompt	{}
+    regsub -all "\[)(]" $prompt {\\&} reprompt
 
     set commands [split $command \;]
     set num_commands [llength $commands]
     for {set i 0} {$i < $num_commands} { incr i} {
-	send "[lindex $commands $i]\r"
+	send -- "[subst -nocommands [lindex $commands $i]]\r"
 	expect {
-	    -re "^\[^\n\r *]*$prompt $"	{}
-	    -re "^\[^\n\r]*$prompt."	{ exp_continue }
-	    -re "(\r\n|\n)"			{ exp_continue }
+	    -re "^\[^\n\r]*$reprompt"		{}
+	    -re "^\[^\n\r ]*>>.*$reprompt"	{ exp_continue }
+	    -re "\[\n\r]+"			{ exp_continue }
 	}
     }
     send "quit\r"
     expect {
+	-re "^WARNING: There are unsaved configuration changes." {
+						 send "y\r"
+						 exp_continue
+						}
 	"\n"					{ exp_continue }
+	"\[^\n\r *]*Session terminated"		{ return 0 }
 	timeout					{ catch {close}; catch {wait};
 						  return 0
 						}
@@ -469,54 +460,57 @@ foreach router [lrange $argv $i end] {
     set router [string tolower $router]
     send_user "$router\n"
 
-    # device timeout
-    set timeout [find timeout $router]
-    if { [llength $timeout] == 0 } {
-	set timeout $timeoutdflt
-    }
+    # Figure out prompt.
+    set prompt "] > "
+    # alteon only "enables" based on the password used at login time
+    set autoenable 1
+    set enable 0
 
-    set prompt ">"
+    # Figure out passwords
+    if { $do_passwd } {
+      set pswd [find password $router]
+      if { [llength $pswd] == 0 } {
+	send_user "\nError - no password for $router in $password_file.\n"
+	continue
+      }
+      set passwd [join [lindex $pswd 0] ""]
+    }
 
     # Figure out username
     if {[info exists username]} {
       # command line username
-      set loginname $username
+      set ruser $username
     } else {
-      set loginname [join [find user $router] ""]
-      if { "$loginname" == "" } { set loginname $default_user }
+      set ruser [join [find user $router] ""]
+      if { "$ruser" == "" } { set ruser $default_user }
     }
 
-    # Figure out loginname's password (if different from the vty password)
+    # Figure out username's password (if different from the vty password)
     if {[info exists userpasswd]} {
-      # command line passwd
-      set passwd $userpasswd
+      # command line username
+      set userpswd $userpasswd
     } else {
-      set passwd [join [lindex [find userpassword $router] 0] ""]
-      if { "$passwd" == "" } {
-        set passwd [join [lindex [find password $router] 0] ""]
-        if { "$passwd" == "" } {
-	  send_user "\nError: no password for $router in $password_file.\n"
-	  continue
-        }
-      }
+      set userpswd [join [find userpassword $router] ""]
+      if { "$userpswd" == "" } { set userpswd $passwd }
     }
 
-    # Figure out identity file to use
-    set identfile [join [lindex [find identity $router] 0] ""]
-
-    # Figure out passphrase to use
-    if {[info exists avpassphrase]} {
-	set passphrase $avpassphrase
+    # Figure out prompts
+    set u_prompt [find userprompt $router]
+    if { "$u_prompt" == "" } {
+	set u_prompt "Login:"
     } else {
-	set passphrase [join [lindex [find passphrase $router] 0] ""]
+	set u_prompt [join [lindex $u_prompt 0] ""]
     }
-    if { ! [string length "$passphrase"]} {
-	set passphrase $passwd
+    set p_prompt [find passprompt $router]
+    if { "$p_prompt" == "" } {
+	set p_prompt "\[Pp]assword:"
+    } else {
+	set p_prompt [join [lindex $p_prompt 0] ""]
     }
 
-    # Figure out ssh cypher type
+    # Figure out cypher type
     if {[info exists cypher]} {
-      # command line ssh cypher type
+      # command line cypher type
       set cyphertype $cypher
     } else {
       set cyphertype [find cyphertype $router]
@@ -532,7 +526,7 @@ foreach router [lrange $argv $i end] {
     if { "$sshcmd" == "" } { set sshcmd {ssh} }
 
     # Login to the router
-    if {[login $router $loginname $passwd $cmethod $cyphertype $identfile]} {
+    if {[login $router $ruser $userpswd $passwd $prompt $cmethod $cyphertype]} {
 	incr exitval
 	continue
     }
@@ -543,10 +537,6 @@ foreach router [lrange $argv $i end] {
 	    continue
 	}
     } elseif { $do_script } {
-	send "set cli complete-on-space off\r"
-	expect -re $prompt	{}
-	send "set cli screen-length 0\r"
-	expect -re $prompt	{}
 	source $sfile
 	catch {close};
     } else {
