Imported from rancid-2.3.2a8.tar.gz.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -700,6 +700,7 @@ MK_LCLSTATEDIR_FALSE
 CONF_INSTALL_TRUE
 CONF_INSTALL_FALSE
 RCSSYS
+SVN_FSTYPE
 MAILPLUS
 ADMINMAILPLUS
 DIRNAME
@@ -1316,10 +1317,15 @@ Optional Features:
                           install time (default: yes)
   --enable-conf-install   enable install of sample .conf files in sysconfdir
                           (default: yes)
-  --enable-svn            enable use of subversion instead of cvs
   --enable-mail-plus      enable mail to rancid+ addresses, instead of rancid-
   --enable-adminmail-plus enable mail to rancid-admin+ addresses, instead of
                           rancid-admin-
+
+Optional Packages:
+  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
+  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-svn=fstype       use subversion instead of cvs, with optional svn
+                          fstype (fsfs|bdb)
 
 Some influential environment variables:
   CC          C compiler command
@@ -4886,9 +4892,10 @@ fi
 
 
 
-for ac_header in errno.h fcntl.h limits.h pty.h malloc.h memory.h siginfo.h \
-		 string.h strings.h stropts.h sys/types.h sys/wait.h unistd.h \
-		 util.h
+
+for ac_header in ctype.h errno.h fcntl.h limits.h pty.h malloc.h memory.h \
+		 siginfo.h string.h strings.h stropts.h sys/types.h \
+		 sys/wait.h unistd.h util.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
@@ -5835,25 +5842,48 @@ fi
 
 
 # Configure for subversion revision control system instead of CVS.
+SVN_FSTYPE="--fs-type fsfs"
 { echo "$as_me:$LINENO: checking whether subversion" >&5
 echo $ECHO_N "checking whether subversion... $ECHO_C" >&6; }
-# Check whether --enable-svn was given.
-if test "${enable_svn+set}" = set; then
-  enableval=$enable_svn; if test "$enable_svn" = yes; then
-    { echo "$as_me:$LINENO: result: yes" >&5
+
+# Check whether --with-svn was given.
+if test "${with_svn+set}" = set; then
+  withval=$with_svn;  case "$withval" in
+  yes)
+	{ echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-    RCSSYS="svn"
-else
-    { echo "$as_me:$LINENO: result: no" >&5
+	RCSSYS="svn"
+	;;
+  fsfs)
+	{ echo "$as_me:$LINENO: result: yes fstype fsfs" >&5
+echo "${ECHO_T}yes fstype fsfs" >&6; }
+	RCSSYS="svn"
+	SVN_FSTYPE="--fs-type fsfs"
+	;;
+  bdb)
+	{ echo "$as_me:$LINENO: result: yes fstype bdb" >&5
+echo "${ECHO_T}yes fstype bdb" >&6; }
+	RCSSYS="svn"
+	SVN_FSTYPE="--fs-type bdb"
+	;;
+  no)
+	{ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-    RCSSYS="cvs"
-fi
+	RCSSYS="cvs"
+	;;
+  *)
+	{ { echo "$as_me:$LINENO: error: unknown svn fs-type $withval" >&5
+echo "$as_me: error: unknown svn fs-type $withval" >&2;}
+   { (exit 1); exit 1; }; }
+  esac
+
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
     RCSSYS="cvs"
 
 fi
+
 
 
 rd_cv_RCSSYS=$RCSSYS
@@ -6982,6 +7012,8 @@ ac_config_files="$ac_config_files bin/agmrancid"
 
 ac_config_files="$ac_config_files bin/alogin bin/arancid"
 
+ac_config_files="$ac_config_files bin/avologin bin/avorancid"
+
 ac_config_files="$ac_config_files bin/blogin bin/brancid"
 
 ac_config_files="$ac_config_files bin/cat5rancid bin/clogin bin/rancid"
@@ -6996,11 +7028,11 @@ ac_config_files="$ac_config_files bin/flogin bin/francid"
 
 ac_config_files="$ac_config_files bin/fnrancid"
 
-ac_config_files="$ac_config_files bin/jlogin bin/jrancid bin/jerancid"
-
 ac_config_files="$ac_config_files bin/hlogin bin/hrancid"
 
 ac_config_files="$ac_config_files bin/htlogin bin/htrancid"
+
+ac_config_files="$ac_config_files bin/jlogin bin/jrancid bin/jerancid"
 
 ac_config_files="$ac_config_files bin/mrancid"
 
@@ -7018,7 +7050,9 @@ ac_config_files="$ac_config_files bin/srancid"
 
 ac_config_files="$ac_config_files bin/tntlogin bin/tntrancid"
 
-ac_config_files="$ac_config_files bin/xrancid bin/zrancid"
+ac_config_files="$ac_config_files bin/xrancid"
+
+ac_config_files="$ac_config_files bin/zrancid"
 
 ac_config_files="$ac_config_files share/rtrfilter"
 
@@ -7629,6 +7663,8 @@ do
     "bin/agmrancid") CONFIG_FILES="$CONFIG_FILES bin/agmrancid" ;;
     "bin/alogin") CONFIG_FILES="$CONFIG_FILES bin/alogin" ;;
     "bin/arancid") CONFIG_FILES="$CONFIG_FILES bin/arancid" ;;
+    "bin/avologin") CONFIG_FILES="$CONFIG_FILES bin/avologin" ;;
+    "bin/avorancid") CONFIG_FILES="$CONFIG_FILES bin/avorancid" ;;
     "bin/blogin") CONFIG_FILES="$CONFIG_FILES bin/blogin" ;;
     "bin/brancid") CONFIG_FILES="$CONFIG_FILES bin/brancid" ;;
     "bin/cat5rancid") CONFIG_FILES="$CONFIG_FILES bin/cat5rancid" ;;
@@ -7641,13 +7677,13 @@ do
     "bin/flogin") CONFIG_FILES="$CONFIG_FILES bin/flogin" ;;
     "bin/francid") CONFIG_FILES="$CONFIG_FILES bin/francid" ;;
     "bin/fnrancid") CONFIG_FILES="$CONFIG_FILES bin/fnrancid" ;;
-    "bin/jlogin") CONFIG_FILES="$CONFIG_FILES bin/jlogin" ;;
-    "bin/jrancid") CONFIG_FILES="$CONFIG_FILES bin/jrancid" ;;
-    "bin/jerancid") CONFIG_FILES="$CONFIG_FILES bin/jerancid" ;;
     "bin/hlogin") CONFIG_FILES="$CONFIG_FILES bin/hlogin" ;;
     "bin/hrancid") CONFIG_FILES="$CONFIG_FILES bin/hrancid" ;;
     "bin/htlogin") CONFIG_FILES="$CONFIG_FILES bin/htlogin" ;;
     "bin/htrancid") CONFIG_FILES="$CONFIG_FILES bin/htrancid" ;;
+    "bin/jlogin") CONFIG_FILES="$CONFIG_FILES bin/jlogin" ;;
+    "bin/jrancid") CONFIG_FILES="$CONFIG_FILES bin/jrancid" ;;
+    "bin/jerancid") CONFIG_FILES="$CONFIG_FILES bin/jerancid" ;;
     "bin/mrancid") CONFIG_FILES="$CONFIG_FILES bin/mrancid" ;;
     "bin/nlogin") CONFIG_FILES="$CONFIG_FILES bin/nlogin" ;;
     "bin/nrancid") CONFIG_FILES="$CONFIG_FILES bin/nrancid" ;;
@@ -7811,6 +7847,7 @@ MK_LCLSTATEDIR_FALSE!$MK_LCLSTATEDIR_FALSE$ac_delim
 CONF_INSTALL_TRUE!$CONF_INSTALL_TRUE$ac_delim
 CONF_INSTALL_FALSE!$CONF_INSTALL_FALSE$ac_delim
 RCSSYS!$RCSSYS$ac_delim
+SVN_FSTYPE!$SVN_FSTYPE$ac_delim
 MAILPLUS!$MAILPLUS$ac_delim
 ADMINMAILPLUS!$ADMINMAILPLUS$ac_delim
 DIRNAME!$DIRNAME$ac_delim
@@ -7821,7 +7858,6 @@ TAR!$TAR$ac_delim
 PERLV_PATH!$PERLV_PATH$ac_delim
 PERLV!$PERLV$ac_delim
 EXPECT_PATH!$EXPECT_PATH$ac_delim
-PING_PATH!$PING_PATH$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -7863,6 +7899,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+PING_PATH!$PING_PATH$ac_delim
 LG_PING_CMD!$LG_PING_CMD$ac_delim
 CVS!$CVS$ac_delim
 SVN!$SVN$ac_delim
@@ -7880,7 +7917,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 15; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 16; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -8452,6 +8489,8 @@ done
     "bin/agmrancid":F) chmod a+x $ac_file ;;
     "bin/alogin":F) chmod a+x $ac_file ;;
     "bin/arancid":F) chmod a+x $ac_file ;;
+    "bin/avologin":F) chmod a+x $ac_file ;;
+    "bin/avorancid":F) chmod a+x $ac_file ;;
     "bin/blogin":F) chmod a+x $ac_file ;;
     "bin/brancid":F) chmod a+x $ac_file ;;
     "bin/cat5rancid":F) chmod a+x $ac_file ;;
@@ -8464,13 +8503,13 @@ done
     "bin/flogin":F) chmod a+x $ac_file ;;
     "bin/francid":F) chmod a+x $ac_file ;;
     "bin/fnrancid":F) chmod a+x $ac_file ;;
-    "bin/jlogin":F) chmod a+x $ac_file ;;
-    "bin/jrancid":F) chmod a+x $ac_file ;;
-    "bin/jerancid":F) chmod a+x $ac_file ;;
     "bin/hlogin":F) chmod a+x $ac_file ;;
     "bin/hrancid":F) chmod a+x $ac_file ;;
     "bin/htlogin":F) chmod a+x $ac_file ;;
     "bin/htrancid":F) chmod a+x $ac_file ;;
+    "bin/jlogin":F) chmod a+x $ac_file ;;
+    "bin/jrancid":F) chmod a+x $ac_file ;;
+    "bin/jerancid":F) chmod a+x $ac_file ;;
     "bin/mrancid":F) chmod a+x $ac_file ;;
     "bin/nlogin":F) chmod a+x $ac_file ;;
     "bin/nrancid":F) chmod a+x $ac_file ;;
